add workflow dispatch condition

diff --git a/.github/workflows/deploy-infra.yml b/.github/workflows/deploy-infra.yml
--- a/.github/workflows/deploy-infra.yml
+++ b/.github/workflows/deploy-infra.yml
@@ -7,6 +7,7 @@ on:
   pull_request:
     branches:
       - main
+  workflow_dispatch:
 
 env:
   AWS_REGION: ap-northeast-1
@@ -42,6 +43,11 @@ jobs:
       matrix:
         account: ${{ fromJson(needs.prepare_matrix.outputs.accounts) }}
     steps:
+    - name: Check user
+      if: github.event_name == 'workflow_dispatch' && github.actor != 'kf3225'
+      run: |
+        echo "Error: Only 'kf3225' can run this workflow"
+        exit 1
     - name: Set account info
       id: account_info
       run: |
diff --git a/.github/workflows/destroy-infra.yml b/.github/workflows/destroy-infra.yml
--- a/.github/workflows/destroy-infra.yml
+++ b/.github/workflows/destroy-infra.yml
@@ -37,6 +37,12 @@ jobs:
       matrix:
         account: ${{ fromJson(needs.prepare_matrix.outputs.accounts) }}
     steps:
+    - name: Check user
+      if: github.actor != 'kf3225'
+      run: |
+        echo "Error: Only 'kf3225' can run this workflow"
+        exit 1
+
     - name: Set account info
       id: account_info
       run: |
